language: node_js
cache:
    directories:
        ~/.npm
notifications:
  email: false
dist: trusty
sudo: required
node_js:
  - "stable"
  - 10
env:
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi) NODE_ENV=$(if [ "$BRANCH" == "master" ]; then echo production; else echo development; fi)
before_install:
  - npm i -g coveralls
install:
  - npm install
script:
  - npm run test
  - npm run docs
after_success: 
  - npm run coverage
  - npm run semantic-release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
    condition: $NODE_ENV = production
  provider: npm
  skip-cleanup: true
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
      branch: master
branches:
  only:
    - master
git:
  depth: 1 
  quiet: true
